# Generated by Django 6.1.1 on 2026-09-20 18:29

import django.core.validators
import django.db.models.deletion
import element.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('numero', models.BigAutoField(primary_key=True, serialize=False, verbose_name='numéro')),
                ('jeton_ecriture', models.CharField(default=element.models.generate_edit_token, editable=False, help_text='Jeton secret permettant de modifier la fiche.', max_length=64, unique=True, verbose_name="jeton d'écriture")),
                ('libelle', models.CharField(max_length=255, verbose_name='libellé')),
                ('nom_deposant', models.CharField(max_length=255, verbose_name='nom du déposant')),
                ('courriel_deposant', models.EmailField(blank=True, max_length=254, verbose_name='courriel du déposant')),
                ('telephone_deposant', models.CharField(blank=True, max_length=30, verbose_name='téléphone du déposant')),
                ('categorie', models.CharField(choices=[('mare', 'Mare'), ('puit_fontaine', 'Puit ou fontaine'), ('ruine_batisse_ancienne', 'Ruine ou Bâtisse ancienne'), ('lavoir', 'Lavoir'), ('arbre_remarquable', 'Arbre remarquable'), ('autre', 'Autre')], max_length=32, verbose_name='catégorie')),
                ('commune_deleguee', models.CharField(choices=[('Chênedouit', 'Chênedouit'), ('La-Forêt-Auvray', 'La-Forêt-Auvray'), ('La-Fresnaye-Aux-Sauvages', 'La-Fresnaye-Aux-Sauvages'), ('Les-Rotours', 'Les-Rotours'), ('Ménil-Jean', 'Ménil-Jean'), ('Putanges-Pont-Ecrepin', 'Putanges-Pont-Ecrepin'), ('Rabodanges', 'Rabodanges'), ('Saint-Aubert', 'Saint-Aubert'), ('Sainte-Croix-Sur-Orne', 'Sainte-Croix-Sur-Orne')], max_length=32, verbose_name='commune déléguée')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='longitude')),
                ('description', models.TextField(verbose_name='description')),
                ('histoire', models.TextField(blank=True, verbose_name='histoire ou anecdote')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
            ],
            options={
                'verbose_name': 'élément de patrimoine',
                'verbose_name_plural': 'éléments de patrimoine',
                'ordering': ('-date_ajout',),
                'indexes': [models.Index(fields=['categorie'], name='element_categorie_idx'), models.Index(fields=['commune_deleguee'], name='element_commune_idx'), models.Index(fields=['date_ajout'], name='element_date_ajout_idx'), models.Index(fields=['latitude', 'longitude'], name='element_coordonnees_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='element_latitude_valid'), models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='element_longitude_valid')],
            },
        ),
        migrations.CreateModel(
            name='Photographie',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='identifiant')),
                ('fichier', models.ImageField(upload_to='elements/%Y/%m/%d/', verbose_name='fichier image')),
                ('commentaire', models.TextField(blank=True, verbose_name='commentaire')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photographies', to='element.element', verbose_name='élément de patrimoine')),
            ],
            options={
                'verbose_name': 'photographie',
                'verbose_name_plural': 'photographies',
                'ordering': ('id',),
                'indexes': [models.Index(fields=['element'], name='photo_element_idx')],
            },
        ),
    ]
