# Generated by Django 6.1.1 on 2026-09-21 13:00

import element.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographie',
            name='fichier',
            field=models.ImageField(upload_to=element.models.photo_upload_to, verbose_name='fichier image'),
        ),
    ]
