# Generated by Django 6.1.1 on 2026-09-21 13:48

import django.db.models.deletion
from django.db import migrations, models


CATEGORIES = (
    ("Mare", "🌊", "#169AEF"),
    ("Puit ou fontaine", "💧", "#0077B6"),
    ("Ruine ou bâtisse ancienne", "🏚️", "#8D5524"),
    ("Lavoir", "🧼", "#009933"),
    ("Arbre remarquable", "🌳", "#78BE00"),
    ("Autre", "❓", "#607D8B"),
)


def seed_categories(apps, schema_editor):
    Categorie = apps.get_model("element", "Categorie")
    for libelle, icone, couleur in CATEGORIES:
        Categorie.objects.create(libelle=libelle, icone=icone, couleur=couleur)


def migrate_element_categories(apps, schema_editor):
    Element = apps.get_model("element", "Element")
    Categorie = apps.get_model("element", "Categorie")
    category_ids = {
        "mare": Categorie.objects.get(libelle="Mare").pk,
        "puit_fontaine": Categorie.objects.get(libelle="Puit ou fontaine").pk,
        "ruine_batisse_ancienne": Categorie.objects.get(
            libelle="Ruine ou bâtisse ancienne"
        ).pk,
        "lavoir": Categorie.objects.get(libelle="Lavoir").pk,
        "arbre_remarquable": Categorie.objects.get(libelle="Arbre remarquable").pk,
        "autre": Categorie.objects.get(libelle="Autre").pk,
    }
    for element in Element.objects.all().iterator():
        element.categorie_temp_id = category_ids.get(element.categorie, category_ids["autre"])
        element.save(update_fields=("categorie_temp",))


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0002_alter_photographie_fichier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100, unique=True, verbose_name='libellé')),
                ('icone', models.CharField(max_length=8, unique=True, verbose_name='icône')),
                ('couleur', models.CharField(max_length=7, unique=True, verbose_name='couleur')),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'catégories',
                'ordering': ('libelle',),
            },
        ),
        migrations.RunPython(seed_categories, migrations.RunPython.noop),
        migrations.AddField(
            model_name='element',
            name='categorie_temp',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='element.categorie',
                verbose_name='catégorie temporaire',
            ),
        ),
        migrations.RunPython(migrate_element_categories, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='element',
            name='categorie',
        ),
        migrations.RenameField(
            model_name='element',
            old_name='categorie_temp',
            new_name='categorie',
        ),
        migrations.AlterField(
            model_name='element',
            name='categorie',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='elements',
                to='element.categorie',
                verbose_name='catégorie',
            ),
        ),
    ]
