# Generated by Django 6.1.1 on 2026-09-21 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0003_categorie_alter_element_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographie',
            name='commentaire',
        ),
    ]
