# Generated by Django 6.1.1 on 2026-09-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0004_remove_photographie_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='is_valide',
            field=models.BooleanField(default=False, help_text="Indique si l'élément peut être affiché publiquement.", verbose_name='validé'),
        ),
        migrations.AddIndex(
            model_name='element',
            index=models.Index(fields=['is_valide'], name='element_is_valide_idx'),
        ),
    ]
