# Generated by Django 6.1.1 on 2026-09-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0006_add_calvaire_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='courriel_deposant',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Votre courriel'),
        ),
        migrations.AlterField(
            model_name='element',
            name='libelle',
            field=models.CharField(max_length=255, verbose_name="Nom de l'élément"),
        ),
        migrations.AlterField(
            model_name='element',
            name='nom_deposant',
            field=models.CharField(max_length=255, verbose_name='Votre nom'),
        ),
        migrations.AlterField(
            model_name='element',
            name='telephone_deposant',
            field=models.CharField(blank=True, max_length=30, verbose_name='Votre téléphone'),
        ),
    ]
